Document: packetflow
Title: Debian packetflow Manual
Author: <insert document author here>
Abstract: This manual describes what packetflow is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/packetflow/packetflow.sgml.gz

Format: postscript
Files: /usr/share/doc/packetflow/packetflow.ps.gz

Format: text
Files: /usr/share/doc/packetflow/packetflow.text.gz

Format: HTML
Index: /usr/share/doc/packetflow/html/index.html
Files: /usr/share/doc/packetflow/html/*.html

  
